### ISSUE TITLE
Result of array access with tainted index not tainted

### ISSUE THREAD

**Issue by wuestholz** [secure-software-engineering/soot-infoflow#31]
It seems that currently the result of an array access will not become tainted if the index into the array is tainted. For instance, in the following code snippet I would expect variable `y` to be tainted:

```Java
public void Test(int[] a)
{
    int x = source();
    int y = a[x];
    sink(y);
}
```

Is this the intended behavior?

**Comment by StevenArzt** [comment]
Implemented.

**Comment by wuestholz** [comment]
@StevenArzt Great! Thank you!

**Comment by wuestholz** [comment]
@StevenArzt What's the reasoning behind only detecting this flow if implicit flow checking is enabled? I would consider this to be an explicit flow since no control flow is involved.

**Comment by StevenArzt** [comment]
That was indeed an interesting decision to make. The problem is that when this new rule gets applied unconditionally, you get lots of unintended flows. If a non-sensitive array element gets tainted only because of its position in the array, but not because the data at that location is itself sensitive, I wouldn't call this an explicit flow either. You are not passing on tainted data here, you are somewhat using "metadata" if you want. I doesn't really fit eiher model. In the end, I put it to the implicit flow section as this would confuse the least amount of users - including our own test cases.

**Comment by wuestholz** [comment]
@StevenArzt Thank you for clarifying. I agree that this flow doesn't necessarily fit very well in either of the two classic types of flow. Have you considered to introduce a "flow level" that's somewhere between the two? I could imagine that the flows from https://github.com/secure-software-engineering/soot-infoflow/issues/29 could also fit into such a category. It would be nice to catch such flows without checking for all implicit flows, but I can see that it might result in too many flows for some users.
