### ISSUE TITLE
Create source for a method argument (incl. any aliases)

### ISSUE THREAD

**Issue by wuestholz** [secure-software-engineering/soot-infoflow#34]
I am trying to create a source for a method argument. I have created a source-sink manager that creates an access path for the argument of a method `void makeSource(Object)`. However, when the method is called with a local variable as the argument it does not seem to taint aliases of that local variable. Is there some way to achieve this? For instance, I would like to see a flow in the following code:

```Java
void M(Cell c) {
  Cell next = c.next;
  makeSource(next);
  sink(c.next);
}
```

**Comment by wuestholz** [comment]
@StevenArzt Thank you very much for fixing this! However, I'm wondering why you are not doing this for strings in the code below:

```Java
if (!TypeUtils.isStringType(vb.getValue().getType()))
								getAliasing().computeAliases(d1, stmt, vb.getValue(),
										res, getManager().getICFG().getMethodOf(stmt), abs);
```

**Comment by StevenArzt** [comment]
Strings are immutable, final objects in Java. Consequently, a source method cannot write sensitive data into an existing string object, it can only replace the whole string. One cannot have a class derived from string that would violate this constraint either. Therefore, passing a string to a method cannot lead to sensitive data ending up in previously-created aliases of that object. In FlowDroid, we exploit this observation to increase performance and avoid unnecessary alias analyses.

**Comment by wuestholz** [comment]
@StevenArzt I see. I had a different use case in mind and didn't think of this. I want to use the method call as an annotation when the entry method is not main. That is, the user knows that a string contains sensitive information, but the method that created/tainted the string is not reachable from the entry method.

I suppose I can cast the string to object before passing it to the `makeSource` method to circumvent your check. Is there a less hacky way to achieve this? Note that I don't want to use an identity method as a source since that requires the location that should be tainted to be writable (e.g., in the example above variable `next` might be declared final).

**Comment by StevenArzt** [comment]
A less hacky way to annotate the string would be to look for all definitions of the string and replace them with calls to your source method, i.e., the source method returns the string you want to taint instead of the original statement that defined the string. For parameters passed to a function, you could simply overwrite the parameter values with the return value of a source function directly at the beginning of the method.

**Comment by wuestholz** [comment]
@StevenArzt Thank you for the suggestion. As far as I can tell, this only seems to work if the definition is reachable from the entry method or if the tainted location is writable. I was hoping for a more uniform way to address this. For instance, this does not seem to work for the entry method below:

```Java
final String x;
String y;

void M() {
  // makeSecret(x);
  // makeSecret(y);
  sink(x);
  sink(y);
}
```

From a user-perspective it would be nice if one could write the commented code above. Would it be possible to provide a way for indicating to the source propagation rule manager that this optimization should not be applied for a given access path?

**Comment by StevenArzt** [comment]
Ah, you also want to have sources in unreachable methods? That is indeed not supported at the moment, because we want to precisely capture the runtime semantics of the program or app under analysis. If a flow can never happen at runtime, because the source is not reachable, we want to exclude it from our result set. Can you implement your own entry point creator (or derive it from one of the existing implementations) to include your methods in the dummy main method? That would probably be the cleanest way, because you need some sort of model what your program lifecycle looks like. The user must somehow know that a string contains sensitive information - and that implies that it is reachable which, in turn, you can encode in the dummy main method.

**Comment by wuestholz** [comment]
@StevenArzt Thank you! I assume that one would need a whole-program taint analysis from main to just figure out which methods go into the dummy main method. However, we want to avoid that overhead and also any imprecision that might be caused by a dummy main method that is too conservative.

Would you be fine with having a flag (e.g., 'includeAliasedImmutableObjects') in class 'SourceInfo' to indicate that this optimization should not be triggered? If so, I would be happy to create a PR.

**Comment by StevenArzt** [comment]
Sure. Please document that option really well and make sure that the old behavior is preserved as the default. I can then merge the PR.

**Comment by wuestholz** [comment]
@StevenArzt Great! Thanks! I have created a [PR](https://github.com/secure-software-engineering/soot-infoflow/pull/36).
